apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/vladimir-evdokimov-pro/02-platform-gitops-config
    targetRevision: main
    path: infrastructure/cert-manager

  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      selfHeal: true
      prune: true