apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: sample-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: 'https://github.com/vladimir-evdokimov-pro/03-sample-app-microservice'
    targetRevision: main
    path: chart
    helm:
      parameters:
        - name: "image.repository"
          value: "europe-west9-docker.pkg.dev/gke-devsecops-stack-26/order-service-repo/sample-app"

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devsecops-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true