apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: sample-app-monitoring
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/vladimir-evdokimov-pro/02-platform-gitops-config.git
    targetRevision: HEAD
    path: infrastructure/sample-app

  destination:
    server: https://kubernetes.default.svc
    namespace: devsecops-app

  syncPolicy:
    automated:
      selfHeal: true
      prune: true